name: Deploy Site

on:
  push:
    branches: [ "master" ] # or "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 73.232.14.178               
          username: ${{ secrets.SERVER_USER }} 
          key: ${{ secrets.SERVER_SSH_KEY }}  
          port: 22                            
          script: |
            cd ${{ secrets.SERVER_PATH }}     # Secret containing the full path to your project folder on the server
            git fetch --all
            git reset --hard origin/master

            # OPTIONAL: WordPress build commands if using themes/plugins
            # cd wp-content/themes/mytheme && npm install && npm run build

            # OPTIONAL: Clear WordPress cache
            # wp cache flush --allow-root